### PR TITLE
reorganize tests in functional areas

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by emiltin** [comment]
fixes #22
hi @otterdahl what do you think of this way of organizing tests? It's also reflected in the yard documentation structure.

**Comment by otterdahl** [comment]
I have only looked at it briefly. I think it is a good effort. But my initial thoughts on organization are:
* It would be logical to move TLC specific tests to `spec/site/tlc/` so that we could add e.g. `spec/site/vms/` in the future.
* I also think that is good to keep the test cases in consecutive order, e.g. A001, A002, A003 and so on (where possible), since this is the way you normally [read the SXL](https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#alarms)
* It is good to separate functional and non-functional tests. For instance, tests that only checks if S0001, S0002 (and so on..) can be requested and the response is valid - and tests that checks a command and status combination, e.g. M0002 (set time plan) and S0014 (get time plan)

**Comment by emiltin** [comment]
Created spec/site/tlc as suggested and also spec/site/core.
I think test are sorted by status/command/alarm code, within rspec each group (functional area).

Regarding functional/not: If we organize tests by functional areas (signal plans, clock, detector logics) etc, then there will be both types of tests within each of these topics. But maybe we can tag tests, so you can run e.g all a quick scan of what statuses it responds to?

Or we can add a folder called like spec/site/tlc/scan and move all the tests that simply check if the site responds into that folder?

**Comment by otterdahl** [comment]
> Regarding functional/not: If we organize tests by functional areas (signal plans, clock, detector logics) etc, then there will be both types of tests within each of these topics. But maybe we can tag tests, so you can run e.g all a quick scan of what statuses it responds to?
> 
> Or we can add a folder called like spec/site/tlc/scan and move all the tests that simply check if the site responds into that folder?

I think both approaches are OK.

I think there is also a need for a category for stress tests, e.g. fill the communication buffer, send random data, etc. But let's test one of these approaches and see if it needs to changed in the future.

**Comment by emiltin** [comment]
alright, then I suggest we merge this. then we have organisation by topic. If/when we need to run e.g all status tests, we can add tags or another folder.

**Pull request merged**
