### PR TITLE
Investigate duplicate connection and "no reply" issue with ITC-2

### PR DESCRIPTION
**Pull request by otterdahl**
Disable alarm for ITC-2 in order to investigate issue #56 and #57.

- Does it make the duplicate connection issue go away?
- Does it make the "No reply from server" issue go away?

### CODE REVIEW

**Comment by otterdahl** [comment]
Without the alarm test, the problems seems gone.

**Comment by emiltin** [comment]
Does it try to open a separate connection when sending alarms? That would be a bug, I suppose.

**Comment by otterdahl** [comment]
Let's re-enable the alarm test. But this time, do not trigger the alarm. Let it time out and see what happens. I've disabled the trigger in the ITC simulator

**Comment by emiltin** [comment]
no double connections this time

**Comment by emiltin** [comment]
how does it trigger the alarm? could it be the case that when you click on the gui, it somehow uses a separate process, causing a separate connection to be opened? Would be a bug.

**Comment by otterdahl** [comment]
> how does it trigger the alarm? could it be the case that when you click on the gui, it somehow uses a separate process, causing a separate connection to be opened? Would be a bug.

It triggers the alarm by:
1. Temporarily change the internal parameter F12DN23 from 0 to 1 using a serial interface. This parameter represent the maximum time for a detector logic to be permanently "on" (active) before a detector fault is set. Value 0 disables this check
```bash
nc localhost $PORT >/dev/null << EOF
LOGIN USER -l 1 [removed]
LOGIN USER -l 2 [removed]
F12DN23=1
EXIT
EOF
```

2. Trigger detector 1 by simulate a mouse press on a specific coordinate in the GUI. It does this using the xdotool
```bash
# GUI coordinates for detector 1
DET_1_XY="121 579"

# Trigger detector 1 (=ON)
function trigger_detector {
        xdotool search --name "ITC Simulator" \
                windowactivate --sync %1 \
                mousemove --sync $DET_1_XY \
                click --clearmodifiers 1 \
                windowactivate $(xdotool getactivewindow)
```

3. Check that the detector has been activated using the serial interface

```bash
# Check status of detector 1 (1=ON, 0=OFF)
function check_detector {
        return `echo -e "LOGIN USER -l 1 [removed]\nLOGIN USER -l 2 [removed]\nDSTAT\n\033\nexit" |
                nc localhost $PORT |
                tail -n 1 |
                awk 'BEGIN { FS = "" } ; { print $6 }'`
}
```
4. Repeat until we're sure that the detector is active
```bash
check_detector
while [ $? -eq 0 ]
do
        trigger_detector
        check_detector
done
```

**Comment by otterdahl** [comment]
The trigger script is sometimes very slow due to `xdotool`. I wonder if speed is a factor? 

I've tried to remove some checks to the script. I'll try running it again

**Comment by emiltin** [comment]
I think we should file double comnnections as a bug in the simulator. No matter what, it's incorrect to connect twice to the same serverl using the same site it.

**Comment by otterdahl** [comment]
> I've tried to remove some checks in the script. I'll try running it again

Without the check. I didn't trigger the alarm at all, so re-enable it again

**Comment by otterdahl** [comment]
I'll try launching to simulator using non-root credentials (using fakechroot rather then chroot). This would allow us to restart the simulator and clear the buffer before each run. I wonder if this changes the outcome.

**Comment by otterdahl** [comment]
Restarting the rsmp service and clearing the buffer has no effect.

**Comment by otterdahl** [comment]
Anyway. I'm closing this PL. It seems to be triggered by the alarm, but I can't find the cause.

**Pull request closed without merging**
