### PR TITLE
add workflow for testing tecsen tmacs supervisor

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by emiltin** [comment]
@mariusrazvanplugaru Cartesio tests are running, but the TMacs runner is not picking up the workflow.

**Comment by mariusrazvanplugaru** [comment]
Cartesio runner is activa and will be active now on server. Removed the old tocken on the PC. Now we are configuring our server and i will start the runner for the tmacs server. I write here when we are ready.

**Comment by mariusrazvanplugaru** [comment]
Now you see all good? 
We see 3 test passed on tmacs server. On RSMP 3.1.5 i saw that the validator make more than one test, it makes also some subscriptions. Should be inserted also in the last version of Core this tests.

**Comment by emiltin** [comment]
It's runnig the supervisor tests, but it seems the connection sequence tests are skipped. I'll look into it later today.

**Comment by mariusrazvanplugaru** [comment]
I saw that also with OFFLINE validator. For RSMP core 3.1.5 the application make more tests.

**Comment by mariusrazvanplugaru** [comment]
After if it is possible, like for Cartesio, we want publish the results of TECSEN TMacs Platform with the green flag on your site.

**Comment by mariusrazvanplugaru** [comment]
Thank you!

**Comment by emiltin** [comment]
> After if it is possible, like for Cartesio, we want publish the results of TECSEN TMacs Platform with the green flag on your site.

Yes, however we will add a note explaining that the number of tests is limited. Passing the current suite of supervisor tests is not a full validation of a supervisor system.

**Comment by mariusrazvanplugaru** [comment]
Ok, thank you again for your full availability!

**Comment by emiltin** [comment]
rebased on master to pull in PR with TMacs running on port 13111

**Comment by emiltin** [comment]
OK, TMacs tests are now running on port 13111, and the Cartesio on port 12111, so they should not interfere.

There are several issues that I will look into: connection tests are not running and output logs are not uploaded correcty.

**Comment by mariusrazvanplugaru** [comment]
You mean that for Supervisor side?

**Comment by mariusrazvanplugaru** [comment]
Hi! Could you please tell me why is failled the nigthtly 22:00 test ? Thank you!

**Comment by emiltin** [comment]
You can see details of test runs yourself by clicking the compliance flag, or going to https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/semaforica_cartesio.yaml?query=event%3Aschedule
Here I'm filtering bty the event 'schedule' to see only the nightly run.

The latest nightly run failed due to an error during the git checkout, which was appearently cancelled:
> Error: The operation was canceled

Not sure why that happened. I requested a re-run of the tests.

**Comment by mariusrazvanplugaru** [comment]
> You can see details of test runs yourself by clicking the compliance flag, or going to https://github.com/rsmp-nordic/rsmp_validator/actions/workflows/semaforica_cartesio.yaml?query=event%3Aschedule Here I'm filtering bty the event 'schedule' to see only the nightly run.
> 
> The latest nightly run failed due to an error during the git checkout, which was appearently cancelled:
> 
> > Error: The operation was canceled
> 
> Not sure why that happened. I'm re-running the tests.

Yes, i know that but i don't understand the details. It seems like an error of the validator. From yesterday when the test was completed i didn't make any change.

**Comment by emiltin** [comment]
Right that particular error is a bit puzzling, and seems to be something internal with GitHub Actions or the git checkout. 
The re-run succeed and the compliance flag is now green at https://rsmp-nordic.org/compliance/

**Comment by mariusrazvanplugaru** [comment]
Thank you for that! When you are available please add also the TMacs on automatically tests at 22:00 with also green flag associated. KR

**Comment by emiltin** [comment]
What Core versions does TMacs support? We can now test on a matrix of core versions.

**Comment by mariusrazvanplugaru** [comment]
> What Core versions does TMacs support? We can now test on a matrix of core versions.
The TMacs Platform supports all versions but we must insert also in our configuration which version to accept. For the moment is set the last one 3.2.2. KR

**Comment by emiltin** [comment]
Can you check that Ruby 3.3.5 is available on your runner server? Tests seems to stall at the step that installs ruby and gems.

**Comment by emiltin** [comment]
> The TMacs Platform supports all versions but we must insert also in our configuration which version to accept. For the moment is set the last one 3.2.2. KR

OK, for now we'll just test 3.2.2, once other thigs have been fixed we can perhaps try more core versions.

**Comment by emiltin** [comment]
Going to merge this, the workflows for TMacs is now running. There are some follow up issue, but going to open new issues for those.

**Pull request merged**
