### PR TITLE
run cartesio on core matrix, add versions

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by mariusrazvanplugaru** [comment]
There is any mode to download the detailed log of the test result?

**Comment by mariusrazvanplugaru** [comment]
I see some errors like **_2024-09-19T05:26:09.608Z  34116  CAR_TC_001           CAR_TC_001           bfe8  Could not send StatusRequest because schema validation failed: /sS/0/sCI, enum,  {"mType":"rSMsg","type":"StatusRequest","cId":"CAR_TC_001","sS":[{"sCI":"S0018","n":"number"}],"mId":"bfe854c6-8ea2-4426-80ae-3fa6474799fd","ntsOId":"","xNId":""}_**

This is an error of validator?

**Comment by mariusrazvanplugaru** [comment]
Same for other errors that happens, 
another example
2**_024-09-19T05:18:41.345Z  34116  CAR_TC_001           CAR_TC_001           bed0  Could not send StatusRequest because schema validation failed: /sS/1/n, enum,  {"mType":"rSMsg","type":"StatusRequest","cId":"CAR_TC_001","sS":[{"sCI":"S0004","n":"outputstatus"},{"sCI":"S0004","n":"extendedoutputstatus"}],"mId":"bed0a6f1-dcf8-4fa5-8405-fd8b7284738a","ntsOId":"","xNId":""}_**

**Comment by emiltin** [comment]
Yes you can download the detailed logs. If you go to a test run like https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10934857360, you will see the log downloads at the botton right.
It can also be viewed online for each test job.

The Cartesio reports that core versions [3.1.2, 3.1.3, 3.1.5, 3.2, 3.2.1, 3.2.2] are support, so not 3.1.4?
We're in the process of enforcing more strict semver format for version strings, which is why "3.2" is rejected. Please use "3.2.0".

**Comment by emiltin** [comment]
> I see some errors like **_2024-09-19T05:26:09.608Z 34116 CAR_TC_001 CAR_TC_001 bfe8 Could not send StatusRequest because schema validation failed: /sS/0/sCI, enum, {"mType":"rSMsg","type":"StatusRequest","cId":"CAR_TC_001","sS":[{"sCI":"S0018","n":"number"}],"mId":"bfe854c6-8ea2-4426-80ae-3fa6474799fd","ntsOId":"","xNId":""}_**
> 
> This is an error of validator?

It looks like an issue with the json schema which the validator uses to the format of all in- and outgoing messages. I'll investigate.

**Comment by mariusrazvanplugaru** [comment]
Please stop all process and re-run. Now i rebooted the controller, 3.1.4 is enabled and 3.2.0 is accepted and sended.

**Comment by emiltin** [comment]
> I see some errors like **_2024-09-19T05:26:09.608Z 34116 CAR_TC_001 CAR_TC_001 bfe8 Could not send StatusRequest because schema validation failed: /sS/0/sCI, enum, {"mType":"rSMsg","type":"StatusRequest","cId":"CAR_TC_001","sS":[{"sCI":"S0018","n":"number"}],"mId":"bfe854c6-8ea2-4426-80ae-3fa6474799fd","ntsOId":"","xNId":""}_**
> 
> This is an error of validator?

Can you provide a link to the test run where you saw this?

**Comment by mariusrazvanplugaru** [comment]
> > I see some errors like **_2024-09-19T05:26:09.608Z 34116 CAR_TC_001 CAR_TC_001 bfe8 Could not send StatusRequest because schema validation failed: /sS/0/sCI, enum, {"mType":"rSMsg","type":"StatusRequest","cId":"CAR_TC_001","sS":[{"sCI":"S0018","n":"number"}],"mId":"bfe854c6-8ea2-4426-80ae-3fa6474799fd","ntsOId":"","xNId":""}_**
> > This is an error of validator?
> 
> Can you provide a link to the test run where you saw this?

This doesn't happen now, in the last test i saw, but was happen some tests ago.
Here the link:
https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10934829269/workflow

**Comment by emiltin** [comment]
Ok. We did work with the schema recently, which is problaby what causes it. Since we don't see this error on recent run, I think it was solved.

**Comment by emiltin** [comment]
I've restarted all test jobs, but it seems the Cartesio is not responding currently.

**Comment by mariusrazvanplugaru** [comment]
> I've restarted all test jobs, but it seems the Cartesio is not responding currently.

Because is running that: 
https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10934857343/job/30355645787

**Comment by emiltin** [comment]
Ah yes, you're right. I'll just let that run.

**Comment by emiltin** [comment]
@mariusrazvanplugaru The Cartesio now passes tests with all core version 👍 would you like this PR merged, so that nightly testing runs on all core versions?

**Comment by mariusrazvanplugaru** [comment]
Thank you @emiltin , you can add it to run nightly. 
KR

**Comment by emiltin** [comment]
Merged.

**Pull request merged**
