### PR TITLE
Increase startup sequence timeout for ITC-3

### PR DESCRIPTION
**Pull request by otterdahl**
Investigate if increase timeout for startup sequence makes ITC-3 pass the test "follow startup sequence after yellow flash"

### CODE REVIEW

**Comment by emiltin** [comment]
the expected startup sequence is defined in config/swarco_itc3.yaml:

```yaml
startup_sequence: 'efg'
```

is 'efg' correct? it looks like all groups switch to 'e' and never progresses.

**Comment by otterdahl** [comment]
> is 'efg' correct? it looks like all groups switch to 'e' and never progresses.

Yes. I think it is. The controller gets stuck in dark mode.

<html>
<body>


e | Start-up interval 1 | Dark or yellow flash |  
-- | -- | -- | --
f | Start-up interval 2 | Vehicles: yellow, Pedestrians: red |  
g | Start-up interval 3 | Red |  


</body>
</html>

I've looked at the web interface of the controller and it seems to have a 'major error' causing this

**Comment by emiltin** [comment]
> We need to switch to normal control without waiting for startup mode to be over

sounds plausiable, we should try to change the test a bit.

**Comment by otterdahl** [comment]
> > We need to switch to normal control without waiting for startup mode to be over
> 
> sounds plausiable, we should try to change the test a bit.

Yes, it fixes it.

**Comment by emiltin** [comment]
nice!

**Pull request merged**
