### PR TITLE
Guides

### PR DESCRIPTION
**Pull request by emiltin**
More documentation on how to use the validator

### CODE REVIEW

**Comment by emiltin** [comment]
@otterdahl as part of documentting configuration, i've cleaned up the configuration system a bit, which means the format of the config files changed somewhat. i've tried to update the dynniq  and swarco configs, but since the github actions don't currently run correctly, it's hard for me to verify them.

**Comment by emiltin** [comment]
Supervisor testing now works again. It required a bit of reworking of the TestSite class which is now split into Validator, Validator::Site and Validator::Supervisor.
The config handling was a bit tricky and I had to change a few things.

**Comment by emiltin** [comment]
It would be nice to add a github action workflow for supervisor testing, ie. start a supervisor using the rsmp gem, then run the rspec tests in spec/supervisor. But anyways this branch is growing too much. I will try to get in finished and merged

**Comment by otterdahl** [comment]
> @otterdahl as part of documentting configuration, i've cleaned up the configuration system a bit, which means the format of the config files changed somewhat. i've tried to update the dynniq and swarco configs, but since the github actions don't currently run correctly, it's hard for me to verify them.

I'll keep an eye on it. There are currently multiple issues with CI TLC's.

**Comment by emiltin** [comment]
hi @otterdahl i would like to merge this branch now. There are issues with swarco/dynniq CI but I don't think they are directly related to changes in this branch.
can we merge this branch, and work on any CI issues in separete issues?

**Comment by emiltin** [comment]
does the equipment use prot 12111?

**Comment by otterdahl** [comment]
> does the equipment use prot 12111?

Yes, the equipment should connect to port 12111. It is the only port defined by RSMP

**Comment by emiltin** [comment]
the equipment does not seem to connect, but maybe this is a known issue.
do you think we can merge this pr?

**Comment by otterdahl** [comment]
> the swarco tlc does not seem to connect, but maybe this is a known issue.
> do you think we can merge this pr?

Yes. I think it is OK to merge

**Pull request merged**
