### PR TITLE
run itc3 and cartesio on a matrix of core verison, but just with one …

### PR DESCRIPTION
**Pull request by emiltin**
…version

### CODE REVIEW

**Comment by emiltin** [comment]
@mariusrazvanplugaru woud you like to test your cartesio with different core version? curently it reports that it suports only the latest 3.2.2.

**Comment by mariusrazvanplugaru** [comment]
Sorry but this will be visible in Compliance page? Actually we can choose manually with one configuration the version of Core, but is possible to change that to be made automatically.

**Comment by emiltin** [comment]
Not yet, but  we plan to expand how results are shown. At the moment, the flag is green if all tests are green, which would mean if tests pass on all core versions.

**Comment by emiltin** [comment]
Do you mean the TLC always uses 3.2.2, regardless of the Version messages exchanged?

**Comment by mariusrazvanplugaru** [comment]
> Not yet, but we plan to expand how results are shown. At the moment, the flag is green if all tests are green, which would mean if tests pass on all core versions.

Ok, it will be great. When you have that we could configure on controller to accept a matrix of versions and we will start to test a set of core versions.

**Comment by emiltin** [comment]
Alright. The workflow already uses a matrix, although only 3.2.2 is currently in the list of core versions to test. So when you like you can do PR with changes at https://github.com/rsmp-nordic/rsmp_validator/blob/main/.github/workflows/semaforica_cartesio.yaml#L22

**Pull request merged**
