### PR TITLE
Refactor and pass with ruby TLC, use gem 0.1.18

### PR DESCRIPTION
**Pull request by emiltin**
Uses the updated 0.1.18 version of the rsmp gem.
Refactors specs to eliminate a ton of duplicated code.
The TestSite helpers has been refactored to fix some issues with how the concurrent async task were used. The RSMP::Supervisor is now kept in a separate async task between tests.

### CODE REVIEW

**Comment by emiltin** [comment]
Once the 0.1.18 PR is merged in the rsmp gem, the Gemfile here needs to be updated to point to master, tag 0.1.18

**Comment by emiltin** [comment]
We should check if this still works when testing equipement. I found some issue with how timeouts are handled.

**Comment by otterdahl** [comment]
The testing equipment/simulator has been set up to follow this branch.
Logs:
- https://otterdahl.org/rsmp_validator_log/rspec-2020-12-15_10-10-40.log
- https://otterdahl.org/rsmp_validator_log/validation-2020-12-15_10-10-39.log

The first alarm test fails due to incorrect time set in the simulator. There is an issue with the simulator which causes it sometimes to set incorrect time
- I believe that the following alarms tests fails due to the reasons discussed in: https://github.com/rsmp-nordic/rsmp_validator/issues/38

**Comment by emiltin** [comment]
Thanks. Where can I find the test log for the main branch?

**Comment by emiltin** [comment]
I think there is some issue with how the rsmp gem or test test framework handles timeouts. I'm tracking that here: https://github.com/rsmp-nordic/rsmp/issues/14
I see a lot of timeouts in the test log. e.g command responses that are not received.

**Comment by otterdahl** [comment]
All the previous logs are from the main branch. You can find them here: https://otterdahl.org/rsmp_validator_log/old/
For instance:
* https://otterdahl.org/rsmp_validator_log/old/rspec-2020-12-14_22-45-51.log
* https://otterdahl.org/rsmp_validator_log/old/validation-2020-12-14_22-45-49.log

**Comment by emiltin** [comment]
ok i see. thank you.

**Comment by otterdahl** [comment]
> > The first alarm test fails due to incorrect time set in the simulator. There is an issue with the simulator which causes it sometimes to set incorrect time
> > 
> > * I believe that the following alarms tests fails due to the reasons discussed in: #38
> 
> It's not too far off though, almost exactly one hour. Could be daylight savings time messing it up maybe?

It's a good guess. But I don't believe so. The problem is that the time stamp used in alarms are not taken from the computers clock itself - it is meant to be taken from an external source (for instance when using connection to traffic simulation software such as vissim) but if there is no external clock source then the simulator needs to keep track of time by itself instead.

Each time the simulator starts, the clock needs to be set manually in the simulator GUI. The default otherwise is 1970-01-01. There is no way to do this using command tools or configuration file - at least not what I have found. The only way to automate this is to use a tool such as `xdotool` which simulates keyboard input and mouse activity. But, due to the nature of simulating input like this - sometimes it doesn't work properly.

I set the time in the GUI by simulating mouse movements and keyboard input using the following shell script:
```bash
#!/bin/bash

# GUI coordinates
HOUR_XY="229 470"  # Hour
SETTIME_XY="112 348" # Set time

HOUR=`date +%H`
MINUTE=`date +%M`
SECOND=`date +%S`

# Set time
function set_time {
        # Start with setting time and hour
        xdotool search --name "ITC Simulator" \
                windowactivate --sync %1 \
                mousemove $SETTIME_XY \
                click --clearmodifiers 1 \
                key --delay 100 Tab Delete Delete \
                type --delay 100 $HOUR

        # Set minute
        xdotool search --name "ITC Simulator" \
                mousemove $SETTIME_XY \
                click --clearmodifiers 1 \
                key --delay 100 Tab Tab Delete Delete \
                type --delay 100 $MINUTE

        # Set second
        xdotool search --name "ITC Simulator" \
                mousemove $SETTIME_XY \
                click --clearmodifiers 1 \
                key --delay 100 Tab Tab Tab Delete Delete \
                type --delay 100 $SECOND

        xdotool search --name "ITC Simulator" \
                mousemove $SETTIME_XY \
                click 1 \
                click 1 \
                windowactivate $(xdotool getactivewindow)
}

set_time
```

**Comment by emiltin** [comment]
David, what test config (yaml file) is used when running the test with the swarco simulator?
There are timeouts while waiting for the site to become ready:
```ruby
@remote_site.wait_for_state :ready, RSMP_CONFIG['ready_timeout']
```
You should keep settings in a file named e.g. swarco_simulator.yaml, and point to that file in config/validator.yaml. Otherwise the default settings in ruby.yaml will be used, and it uses very short timeouts, suitable for testing with the ruby tcl emulator running on the same machine.

**Comment by emiltin** [comment]
Test for M0010 and M0011 are failing due to component id not recocognized:

2020-12-15 09:06:48 UTC  KK+AG9998     <--  b86e  Sent CommandRequest {"mType":"rSMsg","type":"CommandRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001SG001","arg":[{"cCI":"M0010","cO":"setStart","n":"securityCode","v":""},{"cCI":"M0010","cO":"setStart","n":"status","v":"True"}],"m_id":null,"mId":"b86e611e-f929-4906-9cbb-38246aa79b4e"}
=>
2020-12-15 09:06:48 UTC  KK+AG9998     -->        Received MessageNotAck for CommandRequest b86e: Component ID not recognized. {"mType":"rSMsg","type":"MessageNotAck","oMId":"b86e611e-f929-4906-9cbb-38246aa79b4e","rea":"Component ID not recognized."}

This is caused by the config/swarco.yaml file not matching the config in the swarco emulator. In this case it seems that the test expects a signal group with the component id'KK+AG9998=001SG001, but it's not exisisting in the emulator.

**Comment by emiltin** [comment]
M0012 and M0014-21 fail due to NotAck with stating 'SXL code is not part of this component ID'.

It's using componet id 'KK+AG9998=001TC000', the main component. Could this be the emulator not configured correctly somehow? Or does the emulator simply not support these SXL messages?

```
2020-12-15 09:07:28 UTC  KK+AG9998     <--  dceb  Sent CommandRequest {"mType":"rSMsg","type":"CommandRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","arg":[{"cCI":"M0012","cO":"setStart","n":"securityCode","v":""},{"cCI":"M0012","cO":"setStart","n":"status","v":"5,4134,65;5,11"}],"m_id":null,"mId":"dceb733f-75c2-418e-b149-8266263a7d78"}
2020-12-15 09:07:28 UTC  KK+AG9998     -->        Received MessageNotAck for CommandRequest dceb: SXL code is not part of this component ID. {"mType":"rSMsg","type":"MessageNotAck","oMId":"dceb733f-75c2-418e-b149-8266263a7d78","rea":"SXL code is not part of this component ID."}
```

**Comment by emiltin** [comment]
Btw it would be nice if NotAck inluded a standardized error code, argumentError, unsupported, internalError, etc.

**Comment by emiltin** [comment]
When are tests rerun? Om https://otterdahl.org/rsmp_validator_log/ I don't see logs for today, even though I just pushed new commits.

**Comment by emiltin** [comment]
Seems I was just impatient. They're there now.

**Comment by otterdahl** [comment]
@emiltin 
I use the following configuration file:
```yaml
supervisor:
  sites:
    :any:
      plans:
        - 8
        - 9
      traffic_situations:
        - 1
        - 2
      emergency_routes:
        - 1
      inputs:
        - 1
      components:
        main:
          KK+AG9998=001TC000:
        signal_group:
          KK+AG9998=001SG001:
        detector_logic:
          KK+AG9998=001DL001:
  watchdog_interval: 60
  watchdog_interval: 60
  watchdog_timeout: 120
  acknowledgement_timeout: 20
  command_response_timeout: 20
  status_response_timeout: 20
  status_update_timeout: 20

connect_timeout: 120
ready_timeout: 10

command_timeout: 180
status_timeout: 180
status_update_rate: 0   # rsmp only allow integer update rates
subscribe_timeout: 180
alarm_timeout: 200
shutdown_timeout: 180

scripts:
  activate_alarm: '/home/i0davla/activate_alarm.sh'
  deactivate_alarm: '/home/i0davla/deactivate_alarm.sh'
```

**Comment by otterdahl** [comment]
> M0012 and M0014-21 fail due to NotAck stating 'SXL code is not part of this component ID'.

M0012 is not supported by any TLC yet. In the [SXL](https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#m0012) it says: 
_Although this command is intended to be used with coordination it is not actually specified to be used for this yet. It is reserved in the SXL for possible future use._ 

The Swarco simulator is rather old (2017 or earlier). The M0014-21 commands are not supported in this version

**Comment by emiltin** [comment]
ok. for m10-12 we should expect that the tcl does not support it then..? i guess it depends on whether we just want a list ofg what messages it support, or rather want to check against some specific list

**Comment by emiltin** [comment]
Config looks ok, with the first signal group named  'KK+AG9998=001SG001', which is also what's set as the cId in the CommandRequest. Can you check that it matches the config in the swarco emulator?
In the olders log on your server, from sept 17, it's the same error, so is not a problem that was introduces with this PR.

**Comment by otterdahl** [comment]
Config of the Swarco emulator:

```json
{
    "level-1-default-password": "",
    "level-2-default-password": "",
    "server-ip-address": "127.0.0.1",
    "server-port": 12111,
    "site-id": "KK+AG9998",
    "traffic-controller-cid": "KK+AG9998=001TC000",
    "signal-group-cid-prefix": "KK+AG9998=001SG",
    "detector-logics-cid-prefix": "KK+AG9998=001DL",
    "watchdog-interval-in-seconds": 60,
    "watchdog-can-set-time": false,
    "dont-clear-detections-on-query": false,
    "always-send-s0001": true,
    "always-send-s0002": true,
    "always-send-s0003": true,
    "always-send-s0004": true,
    "always-send-s0005": true,
    "always-send-s0006": true,
    "always-send-s0007": true,
    "always-send-s0008": true,
    "always-send-s0009": true,
    "always-send-s0010": true,
    "always-send-s0011": true,
    "always-send-s0012": true,
    "always-send-s0013": true,
    "always-send-s0014": true,
    "always-send-s0015": true,
    "always-send-s0016": false,
    "always-send-s0017": false,
    "always-send-s0018": false,
    "always-send-s0019": false,
    "always-send-s0020": true,
    "always-send-s0021": true,
    "always-send-s0091": true,
    "always-send-s0092": true,
    "always-send-s0095": false,
    "always-send-s0096": true,
    "always-send-s0201": true,
    "always-send-s0202": true,
    "always-send-s0203": true,
    "always-send-s0204": true,
    "hardware-input-mapping": [],
    "database-name": "rsmp-db",
    "max-database-entries": 1000,
    "fbi-ip-address": "127.0.0.1",
    "fbi-port": 4000,
    "fbi-name": "CENTRAL_SYSTEM/rsmp",
    "logging-enabled": true,
    "max-log-entries": 10000,
    "max-logs-uncompressed": 3,
    "max-logs-compressed": 300,
    "rsmp-version": "3.1.2",
    "sxl-version": "1.0.7"
}
```

**Comment by emiltin** [comment]
It's using the prefix KK+AG9998=001SG which looks right, but how is it formatting the signal group number? It should be '001' to match the validator config. We could try using '1' in the validator config to see if that what the emulator expects.

**Comment by otterdahl** [comment]
Done. Running tests again

**Comment by emiltin** [comment]
Hmm, same result. Bug in the emulator, or what component id is it expecting?

**Comment by emiltin** [comment]
merging. let's open new issues for any remaining smaller issues

**Pull request merged**
