### PR TITLE
Add test case for M0023 timeout of dynamic bands

### PR DESCRIPTION
**Pull request by otterdahl**
The M0023 command was added in SXL 1.1. This PR adds a test case for this command

### CODE REVIEW

**Comment by otterdahl** [comment]
The Gem TLC doesn't seem to support M0023 yet

**Comment by emiltin** [comment]
> The Gem TLC doesn't seem to support M0023 yet

right

**Comment by emiltin** [comment]
I added support for M0023 in the gem tlc. It's simplistic, and is not yet actually used in the dynamic bands. But it makes the test pass.

I added a check for setting the timeout to 10 (in addtional to the existing timeout of 0)

**Comment by emiltin** [comment]
rebased on master

**Comment by otterdahl** [comment]
Looks good

**Pull request merged**
