### PR TITLE
S0098 config

### PR DESCRIPTION
**Pull request by otterdahl**
Issue: https://github.com/rsmp-nordic/rsmp_validator/issues/448

Work in progress. It should validate that the response isn't an empty string

### CODE REVIEW

**Comment by otterdahl** [comment]
@emiltin The S0098 status doesn't seem to be implemented in the TLC gem?

**Comment by emiltin** [comment]
> @emiltin The S0098 status doesn't seem to be implemented in the TLC gem?

Right, it just implements enough to pass tests. But I can add support for S0098.

**Comment by emiltin** [comment]
Added suppport for S0098 in the rsmp gem, and pulled it into this PR

**Comment by emiltin** [comment]
I have to leave for today, back tuesday. Thanks for the PR

**Comment by emiltin** [comment]
Gem TCL now passes all tests.

**Comment by otterdahl** [comment]
> The test that was added checks that a status response is received. Should we also check that the received attributes have reasonable values, e.g. are not empty?

Yes. That would be good.

**Comment by emiltin** [comment]
Are there expections for the value of `q` for any of the attributes?

**Comment by emiltin** [comment]
The test now verifies that attributes are not empty.

Should we prevent empty attributes in our schema in the first place?

**Comment by emiltin** [comment]
The ITC-3 seems not to implement S0098, returnin "unknown status ID". It's running SXL 1.0.15, where S0098 should be available, right? At least that's how the test is currently tagged.

**Comment by emiltin** [comment]
@sveitech the ITC-3 seems not to implement S0098?
https://github.com/rsmp-nordic/rsmp_validator/actions/runs/12396523470/job/34604744216?pr=468

**Comment by SwarcoPalm** [comment]
> @sveitech the ITC-3 seems not to implement S0098? https://github.com/rsmp-nordic/rsmp_validator/actions/runs/12396523470/job/34604744216?pr=468

It requires a bit of setup, we will enable it on the test controller

**Comment by emiltin** [comment]
@anezsergi i had to add the 'kapsch-etx' label to the runner again, since it was replaced. Let's see if it picks up jobs now:
https://github.com/rsmp-nordic/rsmp_validator/actions/runs/12396523463/job/34648649864?pr=468

**Comment by anezsergi** [comment]
@emiltin the web show "this job was cancelled"

**Pull request merged**
