### PR TITLE
Refactor tests

### PR DESCRIPTION
**Pull request by emiltin**
A number or refactorings.

- fixes config format problems, now matches format used in rsmp gem
- use async stdin.gets when asking users for input, to avoid stalling rsmp processes
- remove hardcoded detector logic indexes
- remove regex checks on responses, it's covered by the schema validation
- fix regexes
- other fixes

Tested against the ruby TLC, but not yet against hardware

### CODE REVIEW

**Comment by emiltin** [comment]
@otterdahl it would be great if you can try this branch with the swarco simulator and let me know how it works

**Comment by otterdahl** [comment]
@emiltin Sure
```
Using test config config/swarco.yaml
👉 Please activate detector error on equipment. Press enter when ready or 's' to skip:  
....FFFF..FFFFFF.....................FFFFFFFFFF...F.FFFFF...

Failures:

  1) RSMP site commands M0003 set traffic situation
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['s'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0015", "n"=>"status", "s"=>"1"}
     # ./spec/site/command_spec.rb:292:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:290:in `each'
     # ./spec/site/command_spec.rb:290:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:288:in `verify_status'
     # ./spec/site/command_spec.rb:281:in `switch_traffic_situation'
     # ./spec/site/command_spec.rb:443:in `block (4 levels) in <top (required)>'
     # ./spec/site/command_spec.rb:443:in `each'
     # ./spec/site/command_spec.rb:443:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:102:in `block in isolated'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  2) RSMP site commands M0004 restart
     Failure/Error: expect { site.wait_for_state :stopped, RSMP_CONFIG['shutdown_timeout'] }.to_not raise_error
     
       expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `+'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:88:in `reset'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/timer.rb:29:in `initialize'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `new'
         # /var/lib/gems/2.5.0/gems/timers-4.3.0/lib/timers/group.rb:45:in `after'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:259:in `with_timeout'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/wait.rb:7:in `wait_for'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/proxy.rb:338:in `wait_for_state'
         # ./spec/site/command_spec.rb:453:in `block (4 levels) in <top (required)>'
         # ./spec/site/command_spec.rb:453:in `block (3 levels) in <top (required)>'
         # ./spec/support/test_site.rb:102:in `block in isolated'
         # ./spec/support/test_site.rb:24:in `block in within_reactor'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
     # ./spec/site/command_spec.rb:453:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:102:in `block in isolated'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  3) RSMP site commands M0005 activate emergency route
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['s'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0006", "n"=>"status", "s"=>"True"}
     # ./spec/site/command_spec.rb:292:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:290:in `each'
     # ./spec/site/command_spec.rb:290:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:288:in `verify_status'
     # ./spec/site/command_spec.rb:354:in `switch_emergency_route'
     # ./spec/site/command_spec.rb:471:in `block (4 levels) in <top (required)>'
     # ./spec/site/command_spec.rb:471:in `each'
     # ./spec/site/command_spec.rb:471:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:102:in `block in isolated'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  4) RSMP site commands M0006 activate input
     Failure/Error:
       expect do
         response = @site.wait_for_status_update component: @component, sCI: item['sCI'],
           n: item['n'], q:'recent', s:item['s'], timeout: RSMP_CONFIG['status_timeout']
       end.to_not raise_error, "Did not receive status #{item.inspect}"
     
       Did not receive status {"sCI"=>"S0003", "n"=>"inputstatus", "s"=>/^.{0}1/}
     # ./spec/site/command_spec.rb:292:in `block (2 levels) in verify_status'
     # ./spec/site/command_spec.rb:290:in `each'
     # ./spec/site/command_spec.rb:290:in `block in verify_status'
     # ./spec/site/command_spec.rb:7:in `log_confirmation'
     # ./spec/site/command_spec.rb:288:in `verify_status'
     # ./spec/site/command_spec.rb:373:in `switch_input'
     # ./spec/site/command_spec.rb:480:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:102:in `block in isolated'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  5) RSMP site connection Version 3.1.1 exchanges correct connection sequence
     Failure/Error: expect(got).to eq(expected)
     
       expected: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "MessageAck"], ["in", "Watchdog"], ["out", "MessageAck"], ["out", "Watchdog"], ["in", "MessageAck"]]
            got: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "Watchdog"], ["out", "MessageAck"], ["out", "Watchdog"], ["in", "AggregatedStatus"], ["out", "MessageAck"]]
     
       (compared using ==)
     # ./spec/site/connect_spec.rb:7:in `block in check_connection_sequence'
     # ./spec/support/test_site.rb:87:in `block in reconnected'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  6) RSMP site connection Version 3.1.2 exchanges correct connection sequence
     Failure/Error: expect(got).to eq(expected)
     
       expected: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "MessageAck"], ["in", "Watchdog"], ["out", "MessageAck"], ["out", "Watchdog"], ["in", "MessageAck"]]
            got: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "Watchdog"], ["out", "MessageAck"], ["out", "Watchdog"], ["in", "AggregatedStatus"], ["out", "MessageAck"]]
     
       (compared using ==)
     # ./spec/site/connect_spec.rb:7:in `block in check_connection_sequence'
     # ./spec/support/test_site.rb:87:in `block in reconnected'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  7) RSMP site connection Version 3.1.3 exchanges correct connection sequence
     Failure/Error: expect(got).to eq(expected)
     
       expected: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "MessageAck"], ["in", "Watchdog...Ack"], ["out", "Watchdog"], ["in", "MessageAck"], ["in", "AggregatedStatus"], ["out", "MessageAck"]]
            got: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "Watchdog"], ["out", "MessageAc...og"], ["in", "AggregatedStatus"], ["out", "MessageAck"], ["in", "MessageAck"], ["in", "MessageAck"]]
     
       (compared using ==)
     # ./spec/site/connect_spec.rb:7:in `block in check_connection_sequence'
     # ./spec/support/test_site.rb:87:in `block in reconnected'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  8) RSMP site connection Version 3.1.4 exchanges correct connection sequence
     Failure/Error: expect(got).to eq(expected)
     
       expected: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "MessageAck"], ["in", "Watchdog...Ack"], ["out", "Watchdog"], ["in", "MessageAck"], ["in", "AggregatedStatus"], ["out", "MessageAck"]]
            got: [["in", "Version"], ["out", "MessageAck"], ["out", "Version"], ["in", "Watchdog"], ["out", "MessageAc...og"], ["in", "AggregatedStatus"], ["out", "MessageAck"], ["in", "MessageAck"], ["in", "MessageAck"]]
     
       (compared using ==)
     # ./spec/site/connect_spec.rb:7:in `block in check_connection_sequence'
     # ./spec/support/test_site.rb:87:in `block in reconnected'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  9) RSMP site disconnect disconnects if watchdogs are not acknowledged
     Failure/Error: expect { site.wait_for_state :stopping, 60 }.to_not raise_error
     
       expected no Exception, got #<Async::TimeoutError: execution expired> with backtrace:
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:64:in `yield'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/condition.rb:38:in `wait'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/wait.rb:9:in `block in wait_for'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:266:in `with_timeout'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/wait.rb:7:in `wait_for'
         # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/proxy.rb:338:in `wait_for_state'
         # ./spec/site/disconnect_spec.rb:16:in `block (4 levels) in <top (required)>'
         # ./spec/site/disconnect_spec.rb:16:in `block (3 levels) in <top (required)>'
         # ./spec/support/test_site.rb:102:in `block in isolated'
         # ./spec/support/test_site.rb:24:in `block in within_reactor'
         # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
     # ./spec/site/disconnect_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/support/test_site.rb:102:in `block in isolated'
     # ./spec/support/test_site.rb:24:in `block in within_reactor'
     # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  10) RSMP site disconnect disconnects if no watchdogs are send
      Failure/Error: expect { site.wait_for_state :stopping, 180 }.to_not raise_error
      
        expected no Exception, got #<Async::TimeoutError: execution expired> with backtrace:
          # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:64:in `yield'
          # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/condition.rb:38:in `wait'
          # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/wait.rb:9:in `block in wait_for'
          # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/reactor.rb:266:in `with_timeout'
          # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/wait.rb:7:in `wait_for'
          # /home/i0davla/.bundle/ruby/2.5.0/rsmp-c6958824b773/lib/rsmp/proxy.rb:338:in `wait_for_state'
          # ./spec/site/disconnect_spec.rb:25:in `block (4 levels) in <top (required)>'
          # ./spec/site/disconnect_spec.rb:25:in `block (3 levels) in <top (required)>'
          # ./spec/support/test_site.rb:102:in `block in isolated'
          # ./spec/support/test_site.rb:24:in `block in within_reactor'
          # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'
      # ./spec/site/disconnect_spec.rb:25:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:102:in `block in isolated'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  11) RSMP site status S0022 list of time plans
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:660:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  12) RSMP site status S0023 command table
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:690:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  13) RSMP site status S0024 offset time
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:720:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  14) RSMP site status S0025 time-of-green/time-of-red
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Component ID is not recognized.
      # ./spec/site/status_spec.rb:757:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  15) RSMP site status S0026 week time table
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:787:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  16) RSMP site status S0027 time tables
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:817:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  17) RSMP site status S0028 cycle time
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:848:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  18) RSMP site status S0029 forced input status
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:878:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  19) RSMP site status S0091 operator logged in/out OP-panel
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:909:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  20) RSMP site status S0092 operator logged in/out web-interface
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:940:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  21) RSMP site status S0202 traffic counting: vehicle speed
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1067:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  22) RSMP site status S0204 traffic counting: classification
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1137:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  23) RSMP site status S0205 traffic counting: number of vehicles
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1168:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  24) RSMP site status S0206 traffic counting: vehicle speed
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1199:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  25) RSMP site status S0207 traffic counting: occupancy
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1230:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

  26) RSMP site status S0208 traffic counting: classification
      Failure/Error: expect(response).not_to be_a(RSMP::MessageNotAck), "Message rejected: #{response.attributes['rea']}"
        Message rejected: Status parameter is not recognized.
      # ./spec/site/status_spec.rb:1269:in `block (3 levels) in <top (required)>'
      # ./spec/support/test_site.rb:79:in `block in connected'
      # ./spec/support/test_site.rb:24:in `block in within_reactor'
      # /var/lib/gems/2.5.0/gems/async-1.23.0/lib/async/task.rb:255:in `block in make_fiber'

Finished in 14 minutes 48 seconds (files took 0.28461 seconds to load)
60 examples, 26 failures

Failed examples:

rspec ./spec/site/command_spec.rb:439 # RSMP site commands M0003 set traffic situation
rspec ./spec/site/command_spec.rb:447 # RSMP site commands M0004 restart
rspec ./spec/site/command_spec.rb:467 # RSMP site commands M0005 activate emergency route
rspec ./spec/site/command_spec.rb:475 # RSMP site commands M0006 activate input
rspec ./spec/site/connect_spec.rb:13 # RSMP site connection Version 3.1.1 exchanges correct connection sequence
rspec ./spec/site/connect_spec.rb:29 # RSMP site connection Version 3.1.2 exchanges correct connection sequence
rspec ./spec/site/connect_spec.rb:45 # RSMP site connection Version 3.1.3 exchanges correct connection sequence
rspec ./spec/site/connect_spec.rb:63 # RSMP site connection Version 3.1.4 exchanges correct connection sequence
rspec ./spec/site/disconnect_spec.rb:11 # RSMP site disconnect disconnects if watchdogs are not acknowledged
rspec ./spec/site/disconnect_spec.rb:20 # RSMP site disconnect disconnects if no watchdogs are send
rspec ./spec/site/status_spec.rb:645 # RSMP site status S0022 list of time plans
rspec ./spec/site/status_spec.rb:675 # RSMP site status S0023 command table
rspec ./spec/site/status_spec.rb:705 # RSMP site status S0024 offset time
rspec ./spec/site/status_spec.rb:735 # RSMP site status S0025 time-of-green/time-of-red
rspec ./spec/site/status_spec.rb:772 # RSMP site status S0026 week time table
rspec ./spec/site/status_spec.rb:802 # RSMP site status S0027 time tables
rspec ./spec/site/status_spec.rb:833 # RSMP site status S0028 cycle time
rspec ./spec/site/status_spec.rb:863 # RSMP site status S0029 forced input status
rspec ./spec/site/status_spec.rb:893 # RSMP site status S0091 operator logged in/out OP-panel
rspec ./spec/site/status_spec.rb:924 # RSMP site status S0092 operator logged in/out web-interface
rspec ./spec/site/status_spec.rb:1051 # RSMP site status S0202 traffic counting: vehicle speed
rspec ./spec/site/status_spec.rb:1113 # RSMP site status S0204 traffic counting: classification
rspec ./spec/site/status_spec.rb:1152 # RSMP site status S0205 traffic counting: number of vehicles
rspec ./spec/site/status_spec.rb:1183 # RSMP site status S0206 traffic counting: vehicle speed
rspec ./spec/site/status_spec.rb:1214 # RSMP site status S0207 traffic counting: occupancy
rspec ./spec/site/status_spec.rb:1245 # RSMP site status S0208 traffic counting: classification
```

**Comment by emiltin** [comment]
Thank you. Quite a bit there I see. Can you clear the file log/validation.log and rerun the tests, then post the content of log/validation.log to a Gist? That will give me much more info.

**Comment by otterdahl** [comment]
https://gist.github.com/otterdahl/950b538552545961920d58646e6189e6

**Comment by emiltin** [comment]
Thank you. Do all tests pass in the master branch?

A few observations looking at the log file, and the rspec report above:

The TLC sends alarms with "cat"=>"b". According to spec it should be either T or D.

The TLC respond to StatusRequests with "Status parameter is not recognized." I'm not sure what parameter this refers to, but guess its "n"->"status". Example of rejected status request: {"mType":"rSMsg","type":"StatusRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","sS":[{"sCI":"S0022","n":"status"}],"mId":"f48c4142-ff17-4c29-b03d-551a04738775"}

Using M0006 to activate input does not seem to have any effect, even though the equipment confirms the request:
```
2020-04-07 13:00:09 UTC  KK+AG9998     <--  aed2  Sent CommandRequest {"mType":"rSMsg","type":"CommandRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","arg":[{"cCI":"M0006","cO":"setInput","n":"status","v":"True"},{"cCI":"M0006","cO":"setInput","n":"securityCode","v":"default"},{"cCI":"M0006","cO":"setInput","n":"input","v":"0"}],"mId":"aed273e6-b4ca-4b3e-877e-d7f09e567008"}
2020-04-07 13:00:09 UTC  KK+AG9998     -->  4468  Received CommandResponse {"mType":"rSMsg","type":"CommandResponse","mId":"446859fd-2ff0-47b5-b9e9-54b74b0dca63","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","cTS":"2020-04-07T13:00:09.441Z","rvs":[{"cCI":"M0006","age":"recent","n":"status","v":"True"},{"cCI":"M0006","age":"recent","n":"securityCode","v":"default"},{"cCI":"M0006","age":"recent","n":"input","v":"0"}]}
```

**Comment by otterdahl** [comment]
> Thank you. Do all tests pass in the master branch?

No. Almost all tests perfoms similar in the master branch. The TLC doesn't use
the latest version of SXL so many statues are not supported.

> The TLC sends alarms with "cat"=>"b". According to spec it should be either T or D.

Yes. This is a known problem with the TLC

> The TLC respond to StatusRequests with "Status parameter is not recognized." I'm not sure what parameter this refers to, but guess its "n"->"status". Example of rejected status request: {"mType":"rSMsg","type":"StatusRequest","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","sS":[{"sCI":"S0022","n":"status"}],"mId":"f48c4142-ff17-4c29-b03d-551a04738775"}

The statues doesn't exist in the TLC because it uses an older version of the
SXL

> Using M0006 to activate input does not seem to have any effect, even though the equipment confirms the request:

Well, M0006 should work in the TLC, so this issues needs to be investigated
further.

**Comment by emiltin** [comment]
The aim is to validate that this branch works correctly, ie. that the correct set of tests fail/pass. Which ones would you expect to fail/pass?
 
All the connection sequence tests are failing. What version of core/sxl is the emulator implementing?

This one is a bug in the validator, but I will need to rewrite the restart test anyways, to expect all groups to to to red first:

```ruby
  2) RSMP site commands M0004 restart
     Failure/Error: expect { site.wait_for_state :stopped, RSMP_CONFIG['shutdown_timeout'] }.to_not raise_error
     
       expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
```

**Comment by otterdahl** [comment]
> The aim is to validate that this branch works correctly, ie. that the correct set of tests fail/pass. Which ones would you expect to fail/pass?

I could post the log from the master branch, but the master branch depends on a
older version of the RSMP gem, so there is a lot of failures there as well.

* M0003 works, but I don't have a TLC configuration for it.
* M0004 only works if there is a serious error active in the TLC, otherwise it failes
* M0005 works in newer version of the TLC, but not this one
* M0006 should work. Not sure why it fails

> All the connection sequence tests are failing. What version of core/sxl is the emulator implementing?

It should implement 3.1.2 and SXL 1.0.7. It is known not to send connection sequence
correctly

> This one is a bug in the validator, but I will need to rewrite the restart test anyways, to expect all groups to to to red first:
> 
> ```ruby
>   2) RSMP site commands M0004 restart
>      Failure/Error: expect { site.wait_for_state :stopped, RSMP_CONFIG['shutdown_timeout'] }.to_not raise_error
>      
>        expected no Exception, got #<TypeError: nil can't be coerced into Float> with backtrace:
> ```

**Comment by emiltin** [comment]
The error for the test "site commands M0004 restart" is because I removed a hardcodedd timeout. Instead it reads from RSMP_CONFIG['shutdown_timeout']. This is missing from dynniq.yaml and swarco.yaml. I should add checks for missing config variables also, and a check in wait_for_state for nil timeout values.

**Comment by otterdahl** [comment]
For comparison, here is the log from each branch

master: [log](https://gist.github.com/otterdahl/46ac144b767ce2bff76d3a7179d6182d) and [validation.log](https://gist.github.com/otterdahl/10106ed7f9de7abd8d8cf03a86ff87e3)
refactor: [log](https://gist.github.com/otterdahl/aa14c366f6f67d6744003ab58bdbcec6) and [validation.log](https://gist.github.com/otterdahl/c0215f7a33591f33cac80a3aec6abe58)

The RSMP gem set to commit b032666ab4c3e2c980a555bfc06076a45833c988 works with the master branch.

I just found out that M0008 "set detector logic" only seem to work with detector logic 1 with the simulator, and not with detector logic 6 which is currently set.

**Comment by emiltin** [comment]
Thanks for the logs. The only difference is that these tests fail in refactor:
```
rspec ./spec/site/alarm_spec.rb:2 # RSMP site alarm A0301 detector error (hardware)
rspec ./spec/site/command_spec.rb:428 # RSMP site commands M0001 set yellow flash
rspec ./spec/site/command_spec.rb:437 # RSMP site commands M0001 set dark mode
```

For testing yellow flash and dark mode, there seems to be a problem with the code expecting the value to be in the "status" attribute in the status update, when in fact it's in "s", according to the log you posted:
```
Did not receive status {"sCI"=>"S0011", "n"=>"status", "status"=>"^True(,True)+$", "regex"=>1}
```

Are you using the latest commit f3c8099 in the refactor branch? I remove the "regex" option, native regex patterns /.../ are now used instead, by the line from your logs shows the old mechanism.

**Comment by otterdahl** [comment]
Correct. I've made a mistake. I've updated the refactor logs.

refactor: [log](https://gist.github.com/otterdahl/aa14c366f6f67d6744003ab58bdbcec6) and [validation.log](https://gist.github.com/otterdahl/c0215f7a33591f33cac80a3aec6abe58)

**Comment by emiltin** [comment]
Ok, then the same tests fail in refactor and main, so I think we can merge?

**Comment by otterdahl** [comment]
Yes. Go ahead

**Pull request merged**
