### PR TITLE
Alarm suspend

### PR DESCRIPTION
**Pull request by emiltin**
shows how to send an alarm suspend message

### CODE REVIEW

**Comment by emiltin** [comment]
to suspend an alarm, you send an rsmp Alarm mesage, with the  aSp set to 'Suspend. Or use  the RSMP::AlarmSuspend class, which automatically does this.

as usual, to collect responses use an AlarmCollector. if you know the message id (mId), is will cancel if a NotAck is received.

**Comment by emiltin** [comment]
i found that the json schema needs to be updated, because it currently requires all attributes, no matter what the aSp (alarm type) is set to, which is incorrect

**Comment by emiltin** [comment]
currently, there's no method in the rsmp gem specifically for sending alarm suspend message, but perhaps it would be useful. but otherwise it's quite easy to just create an Alarm (or AlarmSupend, etc) object, and send it using Proxy#send_message.

**Comment by emiltin** [comment]
the json schema now support all alarm types

**Comment by emiltin** [comment]
It seems ITC-3 does not respond with an alarm message within 60s when we try to suspend/resume an alarm, we get only a MessageAck. Could this be due to some setting on the TLC?

```
Site::Traffic Light Controller Alarm can be suspended and resumed
    2022-08-24T14:20:11.788Z  46478  KK+AG9998=001TC000   KK+AG9998=001TC000   0618  Sent Alarm  {"mType":"rSMsg","type":"Alarm","ntsOId":"","xNId":"","xACId":"","xNACId":"","aSp":"Resume","cId":"KK+AG9998=001TC000","aCId":"A0301","mId":"06183904-eef0-45c7-8efc-0b04f51dcce5"}
    2022-08-24T14:20:11.788Z  46478  KK+AG9998=001TC000   -                    -     Collect 10a4: Waiting for Alarm {"aCI"=>"A0301", "aSp"=>"Suspend", "sS"=>"suspended"}
    2022-08-24T14:20:11.791Z  46478  KK+AG9998=001TC000   KK+AG9998=001TC000   f3f2  Sent Alarm  {"mType":"rSMsg","type":"Alarm","ntsOId":"","xNId":"","xACId":"","xNACId":"","aSp":"Suspend","mId":"f3f2777a-a78d-47d4-adc6-afe46f167bc3","cId":"KK+AG9998=001TC000","aCId":"A0301"}
    2022-08-24T14:20:11.792Z  46478  KK+AG9998=001TC000   -                    -     Received MessageAck for Alarm 0618  {"mType":"rSMsg","type":"MessageAck","oMId":"06183904-eef0-45c7-8efc-0b04f51dcce5"}
    2022-08-24T14:20:11.809Z  46478  KK+AG9998=001TC000   -                    -     Received MessageAck for Alarm f3f2  {"mType":"rSMsg","type":"MessageAck","oMId":"f3f2777a-a78d-47d4-adc6-afe46f167bc3"}
    2022-08-24T14:21:11.645Z  46478  KK+AG9998=001TC000   -                    8ead  Sent Watchdog  {"mType":"rSMsg","type":"Watchdog","wTs":"2022-08-24T14:21:11.641Z","mId":"8ead2a93-74df-4782-bb17-6a652a61bbb7"}
    2022-08-24T14:21:11.726Z  46478  KK+AG9998=001TC000   -                    -     Received MessageAck for Watchdog 8ead  {"mType":"rSMsg","type":"MessageAck","oMId":"8ead2a93-74df-4782-bb17-6a652a61bbb7"}
  Failure/Error:
    RSMP::AlarmCollector.new(site,
      m_id: suspend.m_id,
      num: 1,
      query: {'aCI'=>alarm_code,'aSp'=>'Suspend','sS'=>'suspended'},
      timeout: Validator.config['timeouts']['alarm']
    ).collect!
  
  RSMP::TimeoutError:
    0 of 1 messages collected
```

**Comment by emiltin** [comment]
@otterdahl i suggest merging this. i rebased and updated a bit to ensure the alarm is resumed, even if the test fails efter suspending. the test currently uses A0301.

**Comment by otterdahl** [comment]
Agreed. OK to merge. Just note that the workflows currently specify to run a single test

**Comment by emiltin** [comment]
> Agreed. OK to merge. Just note that the workflows currently specify to run a single test

i already reversed that, so that all tests are run

**Pull request merged**
