### PR TITLE
Update semaforica_cartesio.yaml with Core version 3.2.2, SXL version …

### PR DESCRIPTION
**Pull request by mariusrazvanplugaru**
…1.2.1

### CODE REVIEW

**Comment by emiltin** [comment]
Is the runner online? It doesn't seem to pick up the workflow.

Can I remove your old runner?

**Comment by mariusrazvanplugaru** [comment]
> Is the runner online? It doesn't seem to pick up the workflow.
> 
> Can I remove your old runner?

Yes you can. Now i see working. Could you confirm?

**Comment by emiltin** [comment]
The recommended way to remove the runner is to run this on your machine:

```
# Remove the runner
$ ./config.sh remove --token <token>
```

Remember to use the old token.

**Comment by emiltin** [comment]
It's still not picking it up, I still see "Waiting for a runner to pick up this job..."
Can Github reach the runner?

**Comment by emiltin** [comment]
I've tried removing and adding the testhub tag to this PR, I think it's now running the tests.

**Comment by mariusrazvanplugaru** [comment]
Ok. With the previous test happens something strange. Made something but not all.

I had this result:
rspec ./spec/site/tlc/io_spec.rb:14 # Site::Traffic Light Controller IO Input is read with S0003
rspec ./spec/site/tlc/io_spec.rb:113 # Site::Traffic Light Controller IO Output is read with S0004
rspec ./spec/site/tlc/signal_plans_spec.rb:44 # Site::Traffic Light Controller Signal Plan list size is read with S0018

but i didn't see the test in detailed mode. Maybe for the reason of connection

**Comment by mariusrazvanplugaru** [comment]
Now i see running.

**Comment by emiltin** [comment]
Not sure, but this test run passed: https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10612145707/job/29413201617?pr=418

All tests green, well done!

It's current doing a new run.

**Comment by mariusrazvanplugaru** [comment]
> Not sure, but this test run passed: https://github.com/rsmp-nordic/rsmp_validator/actions/runs/10612145707/job/29413201617?pr=418
> 
> All tests green, well done!
> 
> It's currently doing a new run.

Yes. Thank you! I saw. We waiting the result. Now is at 3/4 of the procedure i think.

**Comment by emiltin** [comment]
Second run also passed 👍 
Merging this PR.

**Pull request merged**
