### PR TITLE
itc2: Fix workflow

### LINKED ISSUE #261: ITC-2: Some packages could not be installed
from https://github.com/rsmp-nordic/rsmp_validator/actions/runs/5052931260/jobs/9066269254:

```
Run sudo dpkg --add-architecture i386
  sudo dpkg --add-architecture i386
  sudo apt-get update
  sudo apt-get -y install wine32
  shell: /usr/bin/bash -e {0}
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Get:6 http://azure.archive.ubuntu.com/ubuntu jammy/main i386 Packages [1040 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu jammy/restricted i386 Packages [30.4 kB]
Get:8 http://azure.archive.ubuntu.com/ubuntu jammy/universe i386 Packages [7474 kB]
Get:9 http://azure.archive.ubuntu.com/ubuntu jammy/multiverse i386 Packages [112 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [393 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted i386 Packages [28.3 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [611 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse i386 Packages [3884 B]
Hit:14 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-backports/main i386 Packages [33.7 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu jammy-backports/universe i386 Packages [12.7 kB]
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main i386 Packages [212 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted i386 Packages [28.0 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe i386 Packages [529 kB]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse i386 Packages [1028 B]
Get:21 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy/main i386 Packages [2124 B]
Fetched 10.5 MB in 2s (6384 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6:i386 : Depends: libgcc-s1:i386 but it is not going to be installed
 libicu70:i386 : Depends: libgcc-s1:i386 (>= 7) but it is not going to be installed
                 Depends: libstdc++6:i386 (>= 5.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.
```

### PR DESCRIPTION
**Pull request by otterdahl**
- [ ] Fixes #261

### CODE REVIEW

**Comment by emiltin** [comment]
the workflows have been changed, so that the equipment tests run only when on a PR to the `equipment`branch. you can change the base branch of this PR if you like to see the equipment tests run

**Comment by otterdahl** [comment]
> the workflows have been changed, so that the equipment tests run only when on a PR to the `equipment`branch. you can change the base branch of this PR if you like to see the equipment tests run

Yeah. That a better approach...

**Comment by emiltin** [comment]
tests don't start - try rebasing on master and force pushing?

**Comment by emiltin** [comment]
no problem. you can try opening a new PR against equipment to see if the tests run, if you like

**Comment by emiltin** [comment]
the equipment branch has diverged from master. i suggest you rebase (or do a hard reset) on master.

**Pull request merged**
