### PR TITLE
check connection sequence for core 3.2.2

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by emiltin** [comment]
@mariusrazvanplugaru the core 3.2.2 connection test now runs (and passes) on TMacs:
Supervisor Connection Sequence exchanges correct connection sequence of rsmp version 3.2.2

**Comment by mariusrazvanplugaru** [comment]
Thank you for notify @emiltin !
Good when everything is green!

**Comment by emiltin** [comment]
I added TMacs to https://rsmp-nordic.org/compliance/, it should be green after the next nighly run, assuming tests pass.

**Comment by mariusrazvanplugaru** [comment]
> I added TMacs to https://rsmp-nordic.org/compliance/, it should be green after the next nighly run, assuming tests pass.

Great. Could you change only the name in TECSEN TMacs please? Thank you!

**Comment by mariusrazvanplugaru** [comment]
Sorry also for the note of Cartesio 

image

Is Semaforica, not Semaphorica.

**Comment by mariusrazvanplugaru** [comment]
> Sorry also for the note of Cartesio
> 
> image
> 
> Is Semaforica, not Semaphorica.

Thank you!

**Comment by emiltin** [comment]
fixed

**Pull request merged**
