### PR TITLE
Fix 219

### LINKED ISSUE #219: Seting traffic situation is missing the "status" attribute
[M0003](https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.0.15/sxl_traffic_light_controller.html#m0003) (traffic situation) has three arguments:
* status
* securityCod
*  traficsituation.
 
But "status" is missing when setting traffic situation. https://github.com/rsmp-nordic/rsmp_validator/blob/f26e49c2a60c14283761135be98935824608f4a2/spec/support/command_helpers.rb#L66

### PR DESCRIPTION
**Pull request by emiltin**
fixes #219

### CODE REVIEW

**Comment by emiltin** [comment]
No traffic situations are configured for our ITC-2. Does the actual TLC have any configured, so we can test M0003?

**Comment by emiltin** [comment]
Can we configure traffic situations in the ITC-2, so we can test it?

**Comment by emiltin** [comment]
Let's see if the ITC-3 test for traffic situations passes. If it does I will merge this PR.

**Comment by emiltin** [comment]
> Let's see if the ITC-3 test for traffic situations passes. If it does I will merge this PR.

As you saids, it's offline. Can be get in online?

**Comment by otterdahl** [comment]
I spoke with Swarco recently. It's offline due to internal network changes at the office. It's nothing which he personally could do anything about. He said we would contact me when it can get reconnected.

**Pull request merged**
