### PR TITLE
Swarco CI: Investigate why M0001 dark mode fails

### PR DESCRIPTION
**Pull request by otterdahl**
Run just "M0001 set dark mode" to see if it works

### CODE REVIEW

**Comment by otterdahl** [comment]
Running just the test "M0001 dark mode" makes it work. Does the previous test interfere (M0001 yellow flash)?

**Comment by otterdahl** [comment]
This time both "M0001 dark mode" and "M0001 yellow flash" failed. Running it again just to verify

**Comment by otterdahl** [comment]
Still fails. It seems the TLC gets stuck in startup-mode when receiving M0001 command during start-up

**Comment by otterdahl** [comment]
Adding 151d105dab76a0c301cc65a745a4074205dad377 makes M0001 yellow flash work, but no luck with M0001 dark mode yet

**Comment by otterdahl** [comment]
After the TLC has been in "yellow flash" or "dark mode" and is switching back to NormalControl, the TLC first performs the startup sequence/upstart mode (S0005=true) for traffic safety reasons. But, the test continues without S0005 has reached false as seen in the log below.

```
2021-06-30T13:31:34.474Z 39188    KK+AG9998=001TC000 -->  5a97  Received StatusUpdate {"mType":"rSMsg","type":"StatusUpdate","mId":"5a9739fe-5664-45d7-8da0-c186389bff00","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2021-06-30T13:31:34.463Z","sS":[{"sCI":"S0005","n":"status","s":"True","q":"recent"}]}
2021-06-30T13:31:34.475Z 39188    KK+AG9998=001TC000 <--        Sent MessageAck for StatusUpdate 5a97 {"mType":"rSMsg","type":"MessageAck","oMId":"5a9739fe-5664-45d7-8da0-c186389bff00"}
2021-06-30T13:31:34.479Z 39188    KK+AG9998=001TC000 <--  a1d7  Sent StatusUnsubscribe {"mType":"rSMsg","type":"StatusUnsubscribe","ntsOId":"","xNId":"","cId":"KK+AG9998=001TC000","sS":[{"sCI":"S0007","n":"status"},{"sCI":"S0011","n":"status"},{"sCI":"S0005","n":"status"}],"mId":"a1d70f5c-bdd9-4b16-bc95-662181168a1c"}
2021-06-30T13:31:34.479Z 39188    KK+AG9998=001TC000            Dark mode off, yellow flash off, start-up mode off confirmed after 101s
```

**Comment by emiltin** [comment]
It's because it was False a bit earlier:
```
2021-06-30T13:29:53.210Z 39188    KK+AG9998=001TC000 -->  0543  Received StatusUpdate {"mType":"rSMsg","type":"StatusUpdate","mId":"05434432-72aa-4008-9ef6-80245128b950","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2021-06-30T13:29:53.205Z","sS":[{"sCI":"S0007","n":"status","s":"True","q":"recent"},{"sCI":"S0005","n":"status","s":"False","q":"recent"},{"sCI":"S0011","n":"status","s":"True","q":"recent"}]}
```

The way the `wait_for_status()` helper currently works, is once an expected status is seen statuses to be seen, it's removed from the list. So it's "wait for all these status values", but not "at the same time".

```ruby 
    wait_for_status(@task,
      "dark mode off, yellow flash off, start-up mode off",
      [
        {'sCI'=>'S0007','n'=>'status','s'=>/^True(,True)*$/},
        {'sCI'=>'S0011','n'=>'status','s'=>/^False(,False)*$/},
        {'sCI'=>'S0005','n'=>'status','s'=>'False'}
      ]
    )
```

**Comment by emiltin** [comment]
We can add an option to require all status to be in the desired state at the same time, if needed?

**Comment by otterdahl** [comment]
> We can add an option to require all status to be in the desired state at the same time, if needed?

Yes. I think it is needed. As stated in https://github.com/rsmp-nordic/rsmp_validator/issues/49. All given conditions need to be fulfilled at the same time, e.g. S0007=True, S0011=False and S0005=False at the same time.

**Comment by emiltin** [comment]
this hasn't been fixed, i think?

**Comment by emiltin** [comment]
actually, according to the commend at https://github.com/rsmp-nordic/rsmp_validator/issues/49#issuecomment-763433068 waiting for statuses should wait for all of them to be satisfied at the same time, but i can't see that reflected in the code in site_proxy_wait.rb. need to investigate

**Comment by otterdahl** [comment]
Correct. The cause for M0001 has been identified (I think). But it hasn't been fixed yet as far as I know.

**Comment by otterdahl** [comment]
Ok. Great.
However, it still fails. It shows missing watchdog. 
```
    2021-10-08T14:24:00.013Z 46328    KK+AG9998=001TC000       No Watchdog within 120 seconds
    2021-10-08T14:24:00.015Z 46328    KK+AG9998=001TC000       Closing connection to site
```

It then reconnects. This happened 17 times during recent tests. Perhaps the ITC-2/ITC-3 doesn't send watchdog regularly?

**Comment by otterdahl** [comment]
Great. I think we can close this PR now

**Comment by emiltin** [comment]
In the example above, two status messages are received right after each other at the end:

```
    2021-10-29T09:13:31.652Z 53900    KK+AG9998=001TC000 KK+AG9998=001TC000 21d0  Received StatusUpdate {"mType":"rSMsg","type":"StatusUpdate","mId":"21d05dd6-3aff-465e-9310-025911cc877d","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2021-10-29T09:13:31.642Z","sS":[{"sCI":"S0011","n":"status","s":"False","q":"recent"}]}
    2021-10-29T09:13:31.656Z 53900    KK+AG9998=001TC000 KK+AG9998=001TC000 063d  Received StatusUpdate {"mType":"rSMsg","type":"StatusUpdate","mId":"063d81bc-7eeb-4f65-aa68-fc0e48cb8ebd","ntsOId":"KK+AG9998=001TC000","xNId":"","cId":"KK+AG9998=001TC000","sTs":"2021-10-29T09:13:31.643Z","sS":[{"sCI":"S0005","n":"status","s":"True","q":"recent"}]}
```

The collection involved in the test waits for 3 criteria (S0005,  S0007 and S0011). S0007 and S0011 two have already been met earlier with message 2b77.

I think what happens is that the message 21d0 causes the third (and last) criteria to be fulfilled, at which point the collection completes. Right afterwards the message 063d indicates start-up mode is True again. But at that point the collect has already completed and the tests passed.

Btw, in the log shown here, the collect match debug output is shown *before* the message reception, which can be a bit confusing

**Pull request closed without merging**
