### PR TITLE
Kapsch model name

### PR DESCRIPTION
**Pull request by emiltin**

### CODE REVIEW

**Comment by anezsergi** [comment]
@emiltin  the model name is kapsch-etx

**Comment by emiltin** [comment]
@anezsergi I removed the old runner. I think you need to use the old token when you remove it from your machine. Then please reinstall the runner with the name 'kapsch-etx', using the new token I emailed you.

**Comment by anezsergi** [comment]
@emiltin  yes, I used the old token for removing de old runner but it wasn't possible. ok I try to install the new one.

**Comment by anezsergi** [comment]
@emiltin  I just tried and it can't remove the old runner and can't install the new one.

**Comment by emiltin** [comment]
> @emiltin I just tried and it can't remove the old runner and can't install the new one.

check this https://github.com/actions/runner/discussions/1437

**Comment by anezsergi** [comment]
@emiltin yes I deleted .runner and try to install new one. But i have problems after Authentication, maybe i need a new token?

**Comment by emiltin** [comment]
Yes they are time limited. I don't have access to email right now, but use AAAQD4SUDHXD5GAEEKWIAM3HMGZEM. I'll delete this comment when you confirm that you have copied it.

**Comment by anezsergi** [comment]
copied

**Comment by emiltin** [comment]
ok, see if you can install the runner

**Comment by anezsergi** [comment]
@emiltin thanks, it is already installed as kapsch-etx.

**Comment by emiltin** [comment]
Perfect

**Pull request merged**
